obj-y += board.o flash-header-imx51-utsvu.dcd.o
extra-y += flash-header-imx51-utsvu.dcd.S flash-header-imx51-utsvu.dcd
lwl-y += lowlevel.o

obj-$(CONFIG_ARCH_IMX_XLOAD) += flash-header-imx51-utsvu-xload.dcd.o
extra-$(CONFIG_ARCH_IMX_XLOAD) += flash-header-imx51-utsvu-xload.dcd.S flash-header-imx51-utsvu-xload.dcd
